FROM jenkins/jenkins:lts

# Switch to root to install Docker out-of-the-box
USER root

# Install Docker CLI and Docker Compose to enable Docker-in-Docker functionality for building our GenAI images
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh

# Add jenkins user to docker group
RUN usermod -aG docker jenkins

# Drop back to regular Jenkins user
USER jenkins
